<?xml version="1.0" encoding="utf-8"?><Database Name="aspnet-SchoolProjectArosh-20210917073145" Class="MyLINQtoSQLTeacherDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDb)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\aspnet-SchoolProjectArosh-20210917073145.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Teacher" Member="Teachers">
    <Type Name="Teacher">
      <Column Name="TeacherID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FatherName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JoiningDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>